### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by stoivo** [idank/explainshell#162]
Hello

I wanted to create a Dockerfile to run explainshell locally. I am not very good with docker so maybe you would help me out a little?

Dockerfile
```Dockerfile
FROM python:3.4

MAINTAINER Simon Toivo Telhaug  <simon.toivo@example.com>

ADD ./requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip
RUN python --version
RUN pip install -r /tmp/requirements.txt

ADD ./ /opt/webapp/
WORKDIR /opt/webapp
EXPOSE 5000

CMD ["make", "serve"]
# CMD ["python", "app.py"]
```
and I get det following when trying to build
```bash
$ docker build -t explainshell .
Sending build context to Docker daemon 3.571 MB
Step 1 : FROM python:3.4
3.4: Pulling from library/python
...
Removing intermediate container 68d0852b8462
Step 5 : RUN python --version
 ---> Running in 9107aa29433a
Python 3.4.5
 ---> 164548d34350
Removing intermediate container 9107aa29433a
Step 6 : RUN pip install -r /tmp/requirements.txt
 ---> Running in f086bd311b0a
Collecting MarkupSafe==0.23 (from -r /tmp/requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Flask==0.10.1 (from -r /tmp/requirements.txt (line 2))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting nltk==2.0.5 (from -r /tmp/requirements.txt (line 3))
  Downloading nltk-2.0.5.tar.gz (954kB)
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpq38kqtie
    Now working in /tmp/tmpq38kqtie/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-6v_7dv9o/nltk
    creating build
    creating build/src
    creating build/src/docs
    creating build/src/docs/_templates
    creating build/src/docs/_theme
    creating build/src/docs/_theme/nature
    creating build/src/docs/_theme/nature/static
    creating build/src/docs/build
    creating build/src/docs/build/html
    creating build/src/docs/build/html/_sources
    creating build/src/docs/build/html/_static
    creating build/src/setuptools
    creating build/src/setuptools/command
    creating build/src/setuptools/tests
    creating build/src/setuptools/tests/indexes
    creating build/src/setuptools/tests/indexes/test_links_priority
    creating build/src/setuptools/tests/indexes/test_links_priority/simple
    creating build/src/setuptools/tests/indexes/test_links_priority/simple/foobar
    creating build/src/tests
    creating build/src/tests/shlib_test
    copying setuptools/package_index.py -> build/src/setuptools
    copying setuptools/extension.py -> build/src/setuptools
    copying setuptools/depends.py -> build/src/setuptools
    copying setuptools/archive_util.py -> build/src/setuptools
    copying setuptools/__init__.py -> build/src/setuptools
    copying setuptools/sandbox.py -> build/src/setuptools
    copying setuptools/dist.py -> build/src/setuptools
    copying setuptools/tests/test_packageindex.py -> build/src/setuptools/tests
    copying setuptools/tests/test_develop.py -> build/src/setuptools/tests
    copying setuptools/tests/test_easy_install.py -> build/src/setuptools/tests
    copying setuptools/tests/test_upload_docs.py -> build/src/setuptools/tests
    copying setuptools/tests/test_sandbox.py -> build/src/setuptools/tests
    copying setuptools/tests/test_resources.py -> build/src/setuptools/tests
    copying setuptools/tests/server.py -> build/src/setuptools/tests
    copying setuptools/tests/__init__.py -> build/src/setuptools/tests
    copying setuptools/tests/test_build_ext.py -> build/src/setuptools/tests
    copying setuptools/tests/doctest.py -> build/src/setuptools/tests
    copying setuptools/command/install.py -> build/src/setuptools/command
    copying setuptools/command/register.py -> build/src/setuptools/command
    copying setuptools/command/upload.py -> build/src/setuptools/command
    copying setuptools/command/egg_info.py -> build/src/setuptools/command
    copying setuptools/command/install_lib.py -> build/src/setuptools/command
    copying setuptools/command/setopt.py -> build/src/setuptools/command
    copying setuptools/command/upload_docs.py -> build/src/setuptools/command
    copying setuptools/command/rotate.py -> build/src/setuptools/command
    copying setuptools/command/test.py -> build/src/setuptools/command
    copying setuptools/command/build_py.py -> build/src/setuptools/command
    copying setuptools/command/bdist_egg.py -> build/src/setuptools/command
    copying setuptools/command/saveopts.py -> build/src/setuptools/command
    copying setuptools/command/bdist_rpm.py -> build/src/setuptools/command
    copying setuptools/command/easy_install.py -> build/src/setuptools/command
    copying setuptools/command/install_egg_info.py -> build/src/setuptools/command
    copying setuptools/command/__init__.py -> build/src/setuptools/command
    copying setuptools/command/bdist_wininst.py -> build/src/setuptools/command
    copying setuptools/command/alias.py -> build/src/setuptools/command
    copying setuptools/command/build_ext.py -> build/src/setuptools/command
    copying setuptools/command/develop.py -> build/src/setuptools/command
    copying setuptools/command/install_scripts.py -> build/src/setuptools/command
    copying setuptools/command/sdist.py -> build/src/setuptools/command
    copying setuptools/tests/win_script_wrapper.txt -> build/src/setuptools/tests
    copying setuptools/cli.exe -> build/src/setuptools
    copying setuptools/gui.exe -> build/src/setuptools
    copying tests/test_distribute_setup.py -> build/src/tests
    copying tests/install_test.py -> build/src/tests
    copying tests/manual_test.py -> build/src/tests
    copying tests/shlib_test/setup.py -> build/src/tests/shlib_test
    copying tests/shlib_test/test_hello.py -> build/src/tests/shlib_test
    copying tests/shlib_test/hellolib.c -> build/src/tests/shlib_test
    copying tests/shlib_test/hello.c -> build/src/tests/shlib_test
    copying tests/shlib_test/hello.pyx -> build/src/tests/shlib_test
    copying tests/api_tests.txt -> build/src/tests
    RefactoringTool: Skipping optional fixer: buffer
    RefactoringTool: Skipping optional fixer: idioms
    RefactoringTool: Skipping optional fixer: set_literal
    RefactoringTool: Skipping optional fixer: ws_comma
    RefactoringTool: Refactored build/src/tests/api_tests.txt
    RefactoringTool: Files that were modified:
    RefactoringTool: build/src/tests/api_tests.txt
    --- build/src/tests/api_tests.txt (original)
    +++ build/src/tests/api_tests.txt (refactored)
    @@ -39,7 +39,7 @@
         >>> dist.py_version == sys.version[:3]
         True

    -    >>> print dist.platform
    +    >>> print(dist.platform)
         None

     Including various computed attributes::
    @@ -199,7 +199,7 @@
     You can ask a WorkingSet to ``find()`` a distribution matching a requirement::

         >>> from pkg_resources import Requirement
    -    >>> print ws.find(Requirement.parse("Foo==1.0"))    # no match, return None
    +    >>> print(ws.find(Requirement.parse("Foo==1.0")))    # no match, return None
         None

         >>> ws.find(Requirement.parse("Bar==0.9"))  # match, return distribution
    @@ -211,7 +211,7 @@
         >>> try:
         ...     ws.find(Requirement.parse("Bar==1.0"))
         ... except VersionConflict:
    -    ...     print 'ok'
    +    ...     print('ok')
         ok

     You can subscribe a callback function to receive notifications whenever a new
    @@ -219,7 +219,7 @@
     once for each existing distribution in the working set, and then is called
     again for new distributions added thereafter::

    -    >>> def added(dist): print "Added", dist
    +    >>> def added(dist): print("Added", dist)
         >>> ws.subscribe(added)
         Added Bar 0.9
         >>> foo12 = Distribution(project_name="Foo", version="1.2", location="f12")
    copying setuptools/tests/indexes/test_links_priority/external.html -> build/src/setuptools/tests/indexes/test_links_priority
    copying setuptools/tests/indexes/test_links_priority/simple/foobar/index.html -> build/src/setuptools/tests/indexes/test_links_priority/simple/foobar
    copying docs/conf.py -> build/src/docs
    copying docs/python3.txt -> build/src/docs
    copying docs/easy_install.txt -> build/src/docs
    copying docs/setuptools.txt -> build/src/docs
    copying docs/roadmap.txt -> build/src/docs
    copying docs/using.txt -> build/src/docs
    copying docs/index.txt -> build/src/docs
    copying docs/pkg_resources.txt -> build/src/docs
    copying docs/build/html/_sources/python3.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/easy_install.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/setuptools.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/roadmap.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/using.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/index.txt -> build/src/docs/build/html/_sources
    copying docs/build/html/_sources/pkg_resources.txt -> build/src/docs/build/html/_sources
    copying docs/_theme/nature/theme.conf -> build/src/docs/_theme/nature
    copying docs/_theme/nature/static/pygments.css -> build/src/docs/_theme/nature/static
    copying docs/build/html/_static/pygments.css -> build/src/docs/build/html/_static
    copying docs/build/html/_static/nature.css -> build/src/docs/build/html/_static
    copying docs/build/html/_static/basic.css -> build/src/docs/build/html/_static
    copying docs/_theme/nature/static/nature.css_t -> build/src/docs/_theme/nature/static
    copying docs/Makefile -> build/src/docs
    copying docs/_templates/indexsidebar.html -> build/src/docs/_templates
    copying site.py -> build/src
    copying pkg_resources.py -> build/src
    copying setup.py -> build/src
    copying easy_install.py -> build/src
    copying distribute_setup.py -> build/src
    copying DEVGUIDE.txt -> build/src
    copying CHANGES.txt -> build/src
    copying README.txt -> build/src
    copying CONTRIBUTORS.txt -> build/src
    copying MANIFEST.in -> build/src
    copying launcher.c -> build/src
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_suite'
      warnings.warn(msg)
    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: invalid command 'bdist_egg'
    /tmp/pip-build-6v_7dv9o/nltk/distribute-0.6.21-py3.4.egg
    Traceback (most recent call last):
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6v_7dv9o/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-6v_7dv9o/nltk/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    OSError: Could not build the egg.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6v_7dv9o/nltk/
The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1
```

**Comment by idank** [comment]
I'm no docker expert, but:

> Step 5 : RUN python --version
>  ---> Running in 9107aa29433a
> Python 3.4.5

is probably why things are failing. You need Python 2.7.x.

**Comment by stoivo** [comment]
ahh, I change my dockerfile to 
```Dockerfile
FROM python:2.7

MAINTAINER Simon Toivo Telhaug  <simon.toivo@example.com>

ADD ./requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip
RUN python --version
RUN pip install -r /tmp/requirements.txt

ADD ./ /opt/webapp/
WORKDIR /opt/webapp
EXPOSE 5000

CMD ["make", "serve"]
```

Now the docker image build and the front page renders.

When I try to search for something it return with 
```
2016-11-12 14:21:16,110 [INFO] explainshell.store: creating store, db = 'explainshell', host = 'mongodb://localhost'
172.17.0.1 - - [12/Nov/2016 14:21:16] "GET /explain?cmd=cut%20-d%20%27%20%27%20-f%201%20/var/log/apache2/access_logs%20%7C%20uniq%20-c%20%7C%20sort%20-n HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/webapp/explainshell/web/views.py", line 31, in explain
    s = store.store('explainshell', config.MONGO_URI)
  File "/opt/webapp/explainshell/store.py", line 220, in __init__
    self.connection = pymongo.MongoClient(host)
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 352, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: could not connect to localhost:27017: [Errno 111] Connection refused
```

Do know what I need to fix this?

**Comment by arahayrabedian** [comment]
@stoivo i'm not familiar with the architecture of explainshell, but i'm going to guess it needs mongodb, which defaults to localhost and is not going to be running out of the box on the dockerfile you've put together.

I'm happy to help with writing a dockerfile (i used to work with docker extensively) but need to proceed at a slow pace since i'm in the middle of a semester.

my recommendation in a case like this would be to spin up a mongo container external to this current container and link them together in a way you please (docker-compose is built for this specific kind of reason) - you'd have to be careful with persistence though.

**Comment by arahayrabedian** [comment]
looking at the Vagrantfile, looks like mongo is a requirement:
https://github.com/idank/explainshell/blob/master/Vagrantfile#L60

**Comment by idank** [comment]
Indeed. I'm not familiar with docker and the way things are done there, but a standard mongodb install with defaults should do it. I suggest you look at the readme and try to get it working without docker first, it has all the instructions you need.

**Comment by arahayrabedian** [comment]
@stoivo would you object to me making a PR which includes the code above?
@idank would you accept a PR that uses docker-compose to spin up explainshell (not necessarily production-ready)? there will be minor modifications that need to be made to some of the config files.

haven't looked at the details, but need something to distract me from academia and this seems like fun.

**Comment by idank** [comment]
What kind of changes to the config? Can you do the changes inside the Dockerfile so it doesn't affect anything else?

**Comment by arahayrabedian** [comment]
major one i can think of (again, haven't looked at it properly yet) would be to pick up the mongodb host from an environment variable, so it can be configured at the time a docker container is brought up and point to a sister container (or dedicated host, or whatever you want).

so instead of something like:
`MONGO_URI = 'mongodb://localhost'`
i'd convert to
`MONGO_URI = os.getenv('MONGO_URI', 'mongodb://localhost')`

off the top of my head, that would be all, but again, haven't ever run explainshell myself to know for sure.


it's unusual in docker to combine a backing store along with an application in one container, though it's certainly possible it's cludgy.

**Comment by arahayrabedian** [comment]
as for doing changes in teh dockerfile - dockerfile is build time, and this is something we would need to configure at runtime

**Comment by stoivo** [comment]
I created a PR and added the MONGO_URI changes.

**Comment by arahayrabedian** [comment]
:+1: now i get to be bored :)

**Comment by stoivo** [comment]
After looking at this example I don't understand who to specify the IP to the postgres server.

**Comment by stoivo** [comment]
I added a docker-compose.yml in https://github.com/idank/explainshell/pull/163/commits/185484b4bad3faa16bda977e1f10e2c40921af5f

**Comment by arahayrabedian** [comment]
@stoivo put a few notes down on the PR that should answer the question.

I wrote a nice guide a few months back on docker/docker-compose for dev purposes that covers a lot of this if you're interested:
https://arahayrabedian.github.io/docker-compose-for-dev/

**Comment by stoivo** [comment]
I think we can close this one now.
