### ISSUE TITLE
nltk-2.0.5 is obsolete

### ISSUE THREAD

**Issue by Himura2la** [idank/explainshell#261]
https://github.com/nltk/nltk/issues/1879

```
$ pip install -r requirements.txt 
Collecting Flask==0.12
  Downloading Flask-0.12-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 341 kB/s 
Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
Collecting nltk==2.0.5
  Downloading nltk-2.0.5.tar.gz (954 kB)
     |████████████████████████████████| 954 kB 1.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/himura/Documents/Git/explainshell/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w0quh8un/nltk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w0quh8un/nltk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-w0quh8un/nltk/pip-egg-info
         cwd: /tmp/pip-install-w0quh8un/nltk/
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "/tmp/pip-install-w0quh8un/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w0quh8un/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-install-w0quh8un/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-install-w0quh8un/nltk/distribute_setup.py", line 123, in _do_download
        tarball = download_setuptools(version, download_base,
      File "/tmp/pip-install-w0quh8un/nltk/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/usr/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pythoninthegrass** [comment]
I managed to get it working with setting `nltk==3.4.5` — the last version to [support Python 2.7](https://pypi.org/project/nltk/3.4.5/) — in requirements.txt then ran `docker-compose up -d`.

Probably a glass house and prone to failure in the not-so-distant future.

**Comment by cstack** [comment]
This was fixed by https://github.com/idank/explainshell/pull/305 and can be closed
