### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by ballPointPenguin** [idank/explainshell#267]
docker version:
Docker version 19.03.12, build 48a66213fe
docker-compose version:
docker-compose version 1.26.2, build eefe0d31
explainshell sha:
bcad627

output of docker-compose build:
```
db uses an image, skipping
Building web
Step 1/9 : FROM python:2.7
 ---> 68e7be49c28c
Step 2/9 : MAINTAINER Simon Toivo Telhaug <simon.toivo@gmail.com>
 ---> Using cache
 ---> 41d9281386f2
Step 3/9 : RUN apt-get update && apt-get install man-db -y
 ---> Using cache
 ---> b6a297133df4
Step 4/9 : ADD ./requirements.txt /tmp/requirements.txt
 ---> Using cache
 ---> 093efc8fe813
Step 5/9 : RUN pip install --upgrade pip && python --version && pip install -r /tmp/requirements.txt
 ---> Running in 8af43e9e32f7
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading pip-20.2.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.2.1
Python 2.7.18
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Flask==0.12
  Downloading Flask-0.12-py2.py3-none-any.whl (82 kB)
Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
Collecting nltk==2.0.5
  Downloading nltk-2.0.5.tar.gz (954 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uc1Pch/nltk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uc1Pch/nltk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-PM7u4r
         cwd: /tmp/pip-install-uc1Pch/nltk/
    Complete output (24 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uc1Pch/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/local/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install --upgrade pip && python --version && pip install -r /tmp/requirements.txt' returned a non-zero code: 1
```

**Comment by SuperSandro2000** [comment]
The nltk version is stone age old and probably needs an update.

**Comment by idank** [comment]
We should probably make that optional to get a running local version. It's only necessary when adding new man pages.

**Comment by smartmanru** [comment]
edit in requirements.txt nltk==3.1

**Comment by cstack** [comment]
This was fixed by https://github.com/idank/explainshell/pull/244 and can be resolved
